FROM python:3.12-slim

RUN apt-get update &&\
    apt-get install -y procps gcc libc6-dev librdkafka-dev &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /app-sender

COPY requirements.txt /app-sender/
RUN pip install --no-cache-dir -r requirements.txt

COPY sender.py /app-sender/

CMD exec python -u sender.py