FROM python:3.12-slim

RUN apt-get update &&\
    apt-get install -y procps gcc libc6-dev librdkafka-dev &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /app-receiver

COPY requirements.txt /app-receiver/
RUN pip install --no-cache-dir -r requirements.txt

COPY receiver.py /app-receiver/

CMD exec python -u receiver.py